version: "3.8"

services:
    # Servicio traefik requerido solo para que Dokploy no se queje.
    traefik:
        image: traefik
        restart: always
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - dokploy-network # 👈 debe existir esta red en tu server (propia de Dokploy)
        # 🔹 SIN ports (no se expone en 80/443)

    n8n:
        image: docker.n8n.io/n8nio/n8n
        restart: always
        environment:
            - N8N_HOST=n8n.jdevelopmen.xyz
            - N8N_PORT=5678
            - N8N_PROTOCOL=https
            - NODE_ENV=production
            - WEBHOOK_URL=https://n8n.jdevelopmen.xyz/
            - GENERIC_TIMEZONE=America/Bogota
        volumes:
            - n8n_data:/home/node/.n8n
            - ./local-files:/files
        networks:
            - dokploy-network # 👈 misma red que el traefik dummy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.n8n.rule=Host(`n8n.jdevelopmen.xyz`)"
            - "traefik.http.routers.n8n.entrypoints=websecure"
            - "traefik.http.routers.n8n.tls.certresolver=mytlschallenge"
            - "traefik.http.services.n8n.loadbalancer.server.port=5678"

volumes:
    n8n_data:

networks:
    dokploy-network:
        external: true # 👈 esta red la crea Dokploy automáticamente
