version: "3.8"

services:
    # Servicio traefik requerido por Dokploy, pero NO expone puertos
    traefik:
        image: traefik
        restart: always
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        # 🔹 Sin ports aquí, Dokploy ya tiene un Traefik global en 80/443

    # Servicio N8N
    n8n:
        image: docker.n8n.io/n8nio/n8n
        restart: always
        environment:
            - N8N_HOST=n8n.jdevelopmen.xyz # Tu dominio real
            - N8N_PORT=5678
            - N8N_PROTOCOL=https
            - NODE_ENV=production
            - WEBHOOK_URL=https://n8n.jdevelopmen.xyz/
            - GENERIC_TIMEZONE=America/Bogota
        volumes:
            - n8n_data:/home/node/.n8n
            - ./local-files:/files
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.n8n.rule=Host(`n8n.jdevelopmen.xyz`)"
            - "traefik.http.routers.n8n.entrypoints=websecure"
            - "traefik.http.routers.n8n.tls.certresolver=mytlschallenge"
            - "traefik.http.services.n8n.loadbalancer.server.port=5678"

volumes:
    n8n_data:
